# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f4dccc5405c4f5371a4840dedce507f24afb2cc5f63a2d8203a5780061696dcebfe58920899e4a3cff62abfe9aea3cbf0b6084873d3ba45bfc00754cce6b38

test:
  secret_key_base: b9dfb70a817785b4e65fd55ddb7984e36f71257f903d3158bae97756c778a825af05084e77105bbf8fef6e17ad2d09075369f9aa1185e70142ae5f6c0d075471

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
